server:
  port: 8080
spring:
  application:
    name: emp-vue
  redis:
    host: 192.168.245.133 # Redis 主机名或 IP 地址
    port: 6379 # Redis 端口号
    password: hellosun # Redis 认证密码（没有密码则填写 null）
    database: 0 # Redis 数据库编号
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（默认值为 8）
        max-idle: 8 # 连接池最大空闲连接数（默认值为 8）
        min-idle: 0 # 连接池最小空闲连接数（默认值为 0）
        max-wait: -1ms # 连接池最大等待时间（-1 表示无限等待，默认值为 -1）
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.245.133:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5 # 最少连接数
      initial-size: 10 # 初始化连接数
      max-total: 50 # 最大连接数
      max-wait-millis: 2000  # 取得连接的最大等待时间
  jackson:
    time-zone: GMT+8 # 设置时区
    date-format: yyyy-MM-dd # 设置日期时间格式

mybatis-plus:
  type-aliases-package: com.galaxy.empvue.entity
  mapper-locations: classpath:com/galaxy/empvue/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl